name: Deploy to Ubuntu Server (WAR & Tomcat)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set gradlew permissions
      run: chmod +x ./gradlew

    - name: Build WAR with Gradle
      run: ./gradlew clean build

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Add known_hosts
      run: ssh-keyscan -t ed25519 23.234.126.30 >> ~/.ssh/known_hosts

    - name: Deploy WAR to Tomcat server
      run: |
        scp build/libs/*.war ubuntu@23.234.126.30:/home/ubuntu/ROOT.war
        ssh -i ~/.ssh/id_ed25519 ubuntu@23.234.126.30 << 'EOF'
          sudo mv /home/ubuntu/ROOT.war /opt/tomcat/webapps/ROOT.war
          sudo systemctl restart tomcat
        EOF
